### ISSUE TITLE
Fragmenta new doesn't work

### ISSUE THREAD

**Issue by 1lann** [fragmenta/fragmenta#13]
This is caused by `resourceName` not being defined when `new` is called. Perhaps it should be defined somewhere around here: https://github.com/fragmenta/fragmenta/blob/master/new.go#L62-L88

I'm using the HEAD commit in the `master` branch, through `go get -u github.com/fragmenta/fragmenta`

Here are the details of what I did, and my environment.

```
# fragmenta new cms test
10:29:30 Fetching from url: github.com/fragmenta/fragmenta-cms
10:29:30 Creating files at: /Users/jason/Workspace/Go/src/frag/test
10:29:30 Removing all at:/Users/jason/Workspace/Go/src/frag/test/.git
10:29:30 Initialising new git repo at:/Users/jason/Workspace/Go/src/frag/test
10:29:30 Updating import paths to: frag/test
10:29:30 Generating new config at /Users/jason/Workspace/Go/src/frag/test/secrets/fragmenta.json
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.ToCamel(0x0, 0x0, 0xc42010b330, 0x1)
	/Users/jason/Workspace/Go/src/github.com/fragmenta/fragmenta/textual.go:49 +0x280
main.reifyString(0xc42026aa80, 0x937, 0x937, 0xb37)
	/Users/jason/Workspace/Go/src/github.com/fragmenta/fragmenta/generate.go:527 +0x1d2
main.generateCreateSQL(0xc420019440, 0x27, 0x0, 0x0)
	/Users/jason/Workspace/Go/src/github.com/fragmenta/fragmenta/new.go:218 +0x501
main.RunNew(0xc420010240, 0x4, 0x4)
	/Users/jason/Workspace/Go/src/github.com/fragmenta/fragmenta/new.go:88 +0x553
main.main()
	/Users/jason/Workspace/Go/src/github.com/fragmenta/fragmenta/fragmenta.go:69 +0x5db
```

```
# go version
go version go1.8rc1 darwin/amd64
```

```
# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jason/Workspace/Go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
```

**Comment by kennygrant** [comment]
Thanks for the report, looking into it.

**Comment by kennygrant** [comment]
This should now be fixed, thanks for reporting. I'm currently refactoring things a bit and managed to break the secrets generation for new apps.
